blergh

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -42,14 +42,14 @@ jobs:
         uses: salsify/action-detect-and-tag-new-version@v2.0.3
         with:
           version-command: |
-            bash -o pipefail -c "poetry version | awk '{ print \$2 }'"
+            echo "REPO_VERSION=`bash -o pipefail -c "poetry version | awk '{ print \$2 }'"`" >> $GITHUB_ENV
           create-tag: false
       
       # See if detected tag is already on remote
       - name: Check for Tag
         id: check-for-tag
         run: |
-          if git show-ref --tags --verify --quiet "refs/tags/${steps.check-version.outputs.tag}"; then
+          if git show-ref --tags --verify --quiet "refs/tags/${env.REPO_VERSION}"; then
             echo "TAG_EXISTS=true" >> $GITHUB_ENV
           else
             echo "TAG_EXISTS=false" >> $GITHUB_ENV
